Traceback (most recent call last):
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import warnings
warnings.filterwarnings('ignore')

from ostatslib.agents import Agent
from ostatslib.reinforcement_learning_methods import SupportVectorRegression

agent = Agent(rl_method=SupportVectorRegression())
for index, (dataset_type, dataset) in enumerate(datasets):
    agent.train(dataset)

agent.rl_method.fit()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 8[0m
[1;32m      5[0m warnings[38;5;241m.[39mfilterwarnings([38;5;124m'[39m[38;5;124mignore[39m[38;5;124m'[39m)
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mostatslib[39;00m[38;5;21;01m.[39;00m[38;5;21;01magents[39;00m [38;5;28;01mimport[39;00m Agent
[0;32m----> 8[0m [38;5;28;01mfrom[39;00m [38;5;21;01mostatslib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mreinforcement_learning_methods[39;00m [38;5;28;01mimport[39;00m SupportVectorRegression
[1;32m     10[0m agent [38;5;241m=[39m Agent(rl_method[38;5;241m=[39mSupportVectorRegression())
[1;32m     11[0m [38;5;28;01mfor[39;00m index, (dataset_type, dataset) [38;5;129;01min[39;00m [38;5;28menumerate[39m(datasets):

[0;31mModuleNotFoundError[0m: No module named 'ostatslib.reinforcement_learning_methods'
ModuleNotFoundError: No module named 'ostatslib.reinforcement_learning_methods'

