Traceback (most recent call last):
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from ostatslib.agents import PPOAgent
from sklearn.datasets import make_classification
from pandas import DataFrame

import warnings
warnings.filterwarnings('ignore')

# loading trained agent
agent = PPOAgent('../trained_ppo_model.zip')

# generating data
X, y = make_classification()
classification_data = DataFrame(X)
classification_data['result'] = y

# running analysis
classification_analysis = agent.analyze(classification_data)

# printing results
print(classification_analysis.summary())
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[1], line 9[0m
[1;32m      6[0m warnings[38;5;241m.[39mfilterwarnings([38;5;124m'[39m[38;5;124mignore[39m[38;5;124m'[39m)
[1;32m      8[0m [38;5;66;03m# loading trained agent[39;00m
[0;32m----> 9[0m agent [38;5;241m=[39m [43mPPOAgent[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../trained_ppo_model.zip[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     11[0m [38;5;66;03m# generating data[39;00m
[1;32m     12[0m X, y [38;5;241m=[39m make_classification()

File [0;32m~/work/ostatslib/ostatslib/ostatslib/agents/ppo_agent.py:29[0m, in [0;36mPPOAgent.__init__[0;34m(self, path, training_envs_count)[0m
[1;32m     28[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, path: [38;5;28mstr[39m [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;28;01mNone[39;00m, training_envs_count: [38;5;28mint[39m [38;5;241m=[39m [38;5;241m10[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[0;32m---> 29[0m     [38;5;28mself[39m[38;5;241m.[39m__model [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__init__model[49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[43mtraining_envs_count[49m[43m)[49m

File [0;32m~/work/ostatslib/ostatslib/ostatslib/agents/ppo_agent.py:53[0m, in [0;36mPPOAgent.__init__model[0;34m(self, path, training_envs_count)[0m
[1;32m     50[0m     environments [38;5;241m=[39m make_vec_env(GymEnvironment, training_envs_count)
[1;32m     51[0m     [38;5;28;01mreturn[39;00m PPO(POLICY, environments, verbose[38;5;241m=[39m[38;5;241m1[39m, policy_kwargs[38;5;241m=[39mPOLICY_KWARGS)
[0;32m---> 53[0m [38;5;28;01mreturn[39;00m [43mPPO[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43mpath[49m[43m)[49m

File [0;32m~/work/ostatslib/ostatslib/.venv/lib/python3.11/site-packages/stable_baselines3/common/base_class.py:706[0m, in [0;36mBaseAlgorithm.load[0;34m(cls, path, env, device, custom_objects, print_system_info, force_reset, **kwargs)[0m
[1;32m    700[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    701[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe specified policy kwargs do not equal the stored policy kwargs.[39m[38;5;124m"[39m
[1;32m    702[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mStored kwargs: [39m[38;5;132;01m{[39;00mdata[[38;5;124m'[39m[38;5;124mpolicy_kwargs[39m[38;5;124m'[39m][38;5;132;01m}[39;00m[38;5;124m, specified kwargs: [39m[38;5;132;01m{[39;00mkwargs[[38;5;124m'[39m[38;5;124mpolicy_kwargs[39m[38;5;124m'[39m][38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    703[0m     )
[1;32m    705[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mobservation_space[39m[38;5;124m"[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m data [38;5;129;01mor[39;00m [38;5;124m"[39m[38;5;124maction_space[39m[38;5;124m"[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m data:
[0;32m--> 706[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124m"[39m[38;5;124mThe observation_space and action_space were not given, can[39m[38;5;124m'[39m[38;5;124mt verify new environments[39m[38;5;124m"[39m)
[1;32m    708[0m [38;5;66;03m# Gym -> Gymnasium space conversion[39;00m
[1;32m    709[0m [38;5;28;01mfor[39;00m key [38;5;129;01min[39;00m {[38;5;124m"[39m[38;5;124mobservation_space[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124maction_space[39m[38;5;124m"[39m}:

[0;31mKeyError[0m: "The observation_space and action_space were not given, can't verify new environments"

